### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by cheeaun** [engineersftw/thegeekpath#14]
- [x] Open source this repo (public)
- [x] Performance and cross-browser tests
- [x] Check typos
- [x] Reveal @thegeekpath Twitter account (add profile link, description)
- [x] Share on Facebook
- [x] Share on Twitter
- [x] Close #6 
- [x] discuss the order and content of launch

What else?

**Comment by cheeaun** [comment]
<img width="1226" alt="screen shot 2017-02-10 at 8 27 02 pm" src="https://cloud.githubusercontent.com/assets/2296/22826811/5d4516cc-efcf-11e6-8144-bed306e50b66.png">
